Repository cardano-foundation/cardano-deposit-wallet, pull requests merged in 2025-02, with the labels that each got.

#30 Add documentation paragraph to README
  README.md
Labels: documentation

#32 Add mithril support to docker compose
  run/docker/docker-compose.yml
Labels: documentation, CI

#25 Add docker-based installation instructions
  CI/pipelines/main.yml
  CI/scripts/run-md.sh
  site/docs/src/installation/docker.md
  site/docs/test/docker-from-flake.yml
  site/docs/test/docker-from-release.yml
Labels: documentation

#40 Add web UI code
  code/cabal.project
  code/exe/cardano-deposit-wallet-exe.cabal
  code/justfile
  code/nix/project.nix
  code/ui/cardano-deposit-wallet-ui.cabal
  code/ui/data/english.txt
  code/ui/data/images/fake-data.png
  code/ui/data/images/icon.png
  code/ui/golden/BIP32Path.json
  code/ui/src/Cardano/Wallet/UI/Deposit/API.hs
  code/ui/src/Cardano/Wallet/UI/Deposit/API/Addresses/Transactions.hs
  code/ui/src/Cardano/Wallet/UI/Deposit/API/Common.hs
  code/ui/src/Cardano/Wallet/UI/Deposit/API/Deposits/Deposits.hs
  code/ui/src/Cardano/Wallet/UI/Deposit/API/Payments.hs
  code/ui/src/Cardano/Wallet/UI/Deposit/Handlers/Addresses.hs
  code/ui/src/Cardano/Wallet/UI/Deposit/Handlers/Addresses/Transactions.hs
  code/ui/src/Cardano/Wallet/UI/Deposit/Handlers/Deposits/Customers.hs
  code/ui/src/Cardano/Wallet/UI/Deposit/Handlers/Deposits/Times.hs
  code/ui/src/Cardano/Wallet/UI/Deposit/Handlers/Deposits/TxIds.hs
  code/ui/src/Cardano/Wallet/UI/Deposit/Handlers/Lib.hs
  code/ui/src/Cardano/Wallet/UI/Deposit/Handlers/Payments/Balance.hs
  code/ui/src/Cardano/Wallet/UI/Deposit/Handlers/Payments/Transaction.hs
  code/ui/src/Cardano/Wallet/UI/Deposit/Handlers/Wallet.hs
  code/ui/src/Cardano/Wallet/UI/Deposit/Html/Common.hs
  code/ui/src/Cardano/Wallet/UI/Deposit/Html/Pages/About.hs
  code/ui/src/Cardano/Wallet/UI/Deposit/Html/Pages/Addresses.hs
  code/ui/src/Cardano/Wallet/UI/Deposit/Html/Pages/Addresses/Transactions.hs
  code/ui/src/Cardano/Wallet/UI/Deposit/Html/Pages/Deposits/Customers.hs
  code/ui/src/Cardano/Wallet/UI/Deposit/Html/Pages/Deposits/Page.hs
  code/ui/src/Cardano/Wallet/UI/Deposit/Html/Pages/Deposits/Times.hs
  code/ui/src/Cardano/Wallet/UI/Deposit/Html/Pages/Deposits/TxIds.hs
  code/ui/src/Cardano/Wallet/UI/Deposit/Html/Pages/Page.hs
  code/ui/src/Cardano/Wallet/UI/Deposit/Html/Pages/Payments/Page.hs
  code/ui/src/Cardano/Wallet/UI/Deposit/Html/Pages/Wallet.hs
  code/ui/src/Cardano/Wallet/UI/Deposit/Server.hs
  code/ui/src/Cardano/Wallet/UI/Deposit/Server/Addresses.hs
  code/ui/src/Cardano/Wallet/UI/Deposit/Server/Deposits/Customers.hs
  code/ui/src/Cardano/Wallet/UI/Deposit/Server/Deposits/Page.hs
  code/ui/src/Cardano/Wallet/UI/Deposit/Server/Deposits/Times.hs
  code/ui/src/Cardano/Wallet/UI/Deposit/Server/Deposits/TxIds.hs
  code/ui/src/Cardano/Wallet/UI/Deposit/Server/Lib.hs
  code/ui/src/Cardano/Wallet/UI/Deposit/Server/Payments/Page.hs
  code/ui/src/Cardano/Wallet/UI/Deposit/Server/Wallet.hs
  code/ui/src/Cardano/Wallet/UI/Deposit/Types/Payments.hs
  code/ui/src/Cardano/Wallet/UI/Deposit/Types/Wallet.hs
  code/ui/src/Cardano/Wallet/UI/Lib/Discretization.hs
  code/ui/src/Cardano/Wallet/UI/Lib/Pagination/Map.hs
  code/ui/src/Cardano/Wallet/UI/Lib/Pagination/TimedSeq.hs
  code/ui/src/Cardano/Wallet/UI/Lib/Pagination/Type.hs
  code/ui/src/Cardano/Wallet/UI/Lib/Time/Direction.hs
  nix/devShells.nix
Labels: refactoring
